version: '3'
services:
  app:
    #用いるDockerfileの場所を宣言する
    build: ./python 

    #コンテナ内の作業ディレクトリ
    #コマンドでプログラムを実行するときはこのディレクトリの直下に対象のプログラムを入れる
    working_dir: '/root/opt'

    #ホストマシンで公開するポート番号:コンテナのポート番号
    #webアプリの開発・jupyterlabに接続するときなどに使う→しないなら入れなくてもOK
    ports:
       - 8888:8888
    
    #コンテナを起動した後に起動したままにするための設定
    #これがないとコンテナ内に入って操作することができない
    tty: true

    #- ホストマシン側のディレクトリの相対パス：コンテナ内のディレクトリの絶対パス
    #ホストマシン内のディレクトリとコンテナ内のディレクトリを同期する
    #これによってコンテナを閉じた後もコンテナ内での作業がホストマシンのディレクトリに残る（永続化）
    volumes:
      - ./python:/root/opt

    #Pythonのプログラムを自動で実行するコマンド
    #"docker-compose up"で実行結果を確認できる
    command: python sample.py
